module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: './packages',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  testRegex: '.spec.ts$',
  globals: {
    'ts-jest': {
      tsconfig: 'tsconfig.json',
    },
  },
  roots: [
    '<rootDir>/cats/__tests__',
    '<rootDir>/cats/core/src',
    '<rootDir>/cats/free/src',
    '<rootDir>/cats/laws/src',
    '<rootDir>/core/src',
    '<rootDir>/effect/__tests__',
    '<rootDir>/effect/core/src',
    '<rootDir>/effect/kernel/src',
    '<rootDir>/effect/laws/src',
    '<rootDir>/effect/std/src',
    '<rootDir>/stream/__tests__',
    '<rootDir>/stream/core/src',
  ],
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@fp4ts/cats$': '<rootDir>/cats',
    '^@fp4ts/cats-core$': '<rootDir>/cats/core/src',
    '^@fp4ts/cats-core/lib/(.*)$': '<rootDir>/cats/core/src/$1/',
    '^@fp4ts/cats-free$': '<rootDir>/cats/free/src',
    '^@fp4ts/cats-free/lib/(.*)$': '<rootDir>/cats/free/src/$1/',
    '^@fp4ts/cats-laws$': '<rootDir>/cats/laws/src',
    '^@fp4ts/cats-laws/lib/(.*)$': '<rootDir>/cats/laws/src/$1/',
    '^@fp4ts/cats-test-kit$': '<rootDir>/cats/test-kit/src',
    '^@fp4ts/cats-test-kit/lib/(.*)$': '<rootDir>/cats/test-kit/src/$1/',
    '^@fp4ts/core$': '<rootDir>/core/src',
    '^@fp4ts/core/lib/(.*)$': '<rootDir>/core/src/$1/',
    '^@fp4ts/effect$': '<rootDir>/effect',
    '^@fp4ts/effect-core$': '<rootDir>/effect/core/src',
    '^@fp4ts/effect-core/lib/(.*)$': '<rootDir>/effect/core/src/$1/',
    '^@fp4ts/effect-kernel$': '<rootDir>/effect/kernel/src',
    '^@fp4ts/effect-kernel/lib/(.*)$': '<rootDir>/effect/kernel/src/$1/',
    '^@fp4ts/effect-laws$': '<rootDir>/effect/laws/src',
    '^@fp4ts/effect-laws/lib/(.*)$': '<rootDir>/effect/laws/src/$1/',
    '^@fp4ts/effect-std$': '<rootDir>/effect/std/src',
    '^@fp4ts/effect-std/lib/(.*)$': '<rootDir>/effect/std/src/$1/',
    '^@fp4ts/effect-test-kit$': '<rootDir>/effect/test-kit/src',
    '^@fp4ts/effect-test-kit/lib/(.*)$': '<rootDir>/effect/test-kit/src/$1/',
    '^@fp4ts/stream$': '<rootDir>/stream',
    '^@fp4ts/stream-core$': '<rootDir>/stream/core/src',
    '^@fp4ts/stream-core/lib/(.*)$': '<rootDir>/stream/core/src/$1/',
    '^@fp4ts/stream-test-kit$': '<rootDir>/stream/test-kit/src',
    '^@fp4ts/stream-test-kit/lib/(.*)$': '<rootDir>/stream/test-kit/src/$1/',
  },
};
