name: Publish Nightly
on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: 'https://registry.npmjs.org'
        scope: '@fp4ts'
    - name: Install and Build
      env:
        NODE_OPTIONS: '--max_old_space_size=16384'
      run: |
        yarn install --immutable
        yarn compile
    - name: Publish Packages
      run: yarn publish "0.0.1-dev.$(date '+%Y%m%d%H%M')" "next"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
